baseURL = "https://banak.github.io/"
title = "Banak"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 6
enableEmoji = true

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup.highlight]
noClasses = false

[params]
author = "Nathanaël Chansard"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
keywords = "blog,developer,personal"
info = ["Security engineer"]
avatarURL = "background/Banak.png"
dateFormat = "January 2, 2006"
since = 2019
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/nathanaelchansard/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Articles"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Hackthebox"
weight = 4
url = "htb/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

[languages.fr]
languageName = ":fr:"
title = "Banak"

[languages.fr.params]
author = "Nathanaël Chansard"
info = "Ingénieur cybersécurité"

[[languages.fr.menu.main]]
name = "A propos"
weight = 1
url = "about/"

[[languages.fr.menu.main]]
name = "Articles"
weight = 2
url = "posts/"

[[languages.fr.menu.main]]
name = "Hackthebox"
weight = 4
url = "htb/"

[[languages.fr.menu.main]]
name = "Me contacter"
weight = 5
url = "contact/"
